# SPDX-FileCopyrightText: Contributors to the HPCToolkit Project
#
# SPDX-License-Identifier: MIT

libebl_backends_lib = static_library(
  'ebl_backends',
  'i386_init.c',
  'i386_symbol.c',
  'i386_corenote.c',
  'i386_cfi.c',
  'i386_retval.c',
  'i386_regs.c',
  'i386_auxv.c',
  'i386_initreg.c',
  'i386_unwind.c',
  'sh_init.c',
  'sh_symbol.c',
  'sh_corenote.c',
  'sh_regs.c',
  'sh_retval.c',
  'x86_64_init.c',
  'x86_64_symbol.c',
  'x86_64_corenote.c',
  'x86_64_cfi.c',
  'x86_64_retval.c',
  'x86_64_regs.c',
  'x86_64_initreg.c',
  'x86_64_unwind.c',
  'x32_corenote.c',
  'ia64_init.c',
  'ia64_symbol.c',
  'ia64_regs.c',
  'ia64_retval.c',
  'alpha_init.c',
  'alpha_symbol.c',
  'alpha_retval.c',
  'alpha_regs.c',
  'alpha_corenote.c',
  'alpha_auxv.c',
  'arm_init.c',
  'arm_symbol.c',
  'arm_regs.c',
  'arm_corenote.c',
  'arm_auxv.c',
  'arm_attrs.c',
  'arm_retval.c',
  'arm_cfi.c',
  'arm_initreg.c',
  'arm_machineflagname.c',
  'aarch64_init.c',
  'aarch64_regs.c',
  'aarch64_symbol.c',
  'aarch64_corenote.c',
  'aarch64_retval.c',
  'aarch64_cfi.c',
  'aarch64_initreg.c',
  'aarch64_unwind.c',
  'sparc_init.c',
  'sparc_symbol.c',
  'sparc_regs.c',
  'sparc_retval.c',
  'sparc_corenote.c',
  'sparc64_corenote.c',
  'sparc_auxv.c',
  'sparc_attrs.c',
  'sparc_cfi.c',
  'sparc_initreg.c',
  'ppc_init.c',
  'ppc_symbol.c',
  'ppc_retval.c',
  'ppc_regs.c',
  'ppc_corenote.c',
  'ppc_auxv.c',
  'ppc_attrs.c',
  'ppc_cfi.c',
  'ppc_initreg.c',
  'ppc64_init.c',
  'ppc64_symbol.c',
  'ppc64_retval.c',
  'ppc64_corenote.c',
  'ppc64_unwind.c',
  'ppc64_resolve_sym.c',
  's390_init.c',
  's390_symbol.c',
  's390_regs.c',
  's390_retval.c',
  's390_corenote.c',
  's390x_corenote.c',
  's390_cfi.c',
  's390_initreg.c',
  's390_unwind.c',
  'm68k_init.c',
  'm68k_symbol.c',
  'm68k_regs.c',
  'm68k_retval.c',
  'm68k_corenote.c',
  'm68k_cfi.c',
  'm68k_initreg.c',
  'bpf_init.c',
  'bpf_regs.c',
  'bpf_symbol.c',
  'riscv_init.c',
  'riscv_symbol.c',
  'riscv_cfi.c',
  'riscv_regs.c',
  'riscv_initreg.c',
  'riscv_corenote.c',
  'riscv64_corenote.c',
  'riscv_retval.c',
  'csky_attrs.c',
  'csky_init.c',
  'csky_symbol.c',
  'csky_cfi.c',
  'csky_regs.c',
  'csky_initreg.c',
  'csky_corenote.c',
  'loongarch_init.c',
  'loongarch_symbol.c',
  'loongarch_cfi.c',
  'loongarch_regs.c',
  'loongarch_retval.c',
  'loongarch_initreg.c',
  'loongarch_unwind.c',
  'loongarch_corenote.c',
  'arc_init.c',
  'arc_symbol.c',
  pic: true,
  include_directories: include_directories(
    '../libebl',
    '../libasm',
    '../libelf',
    '../libdw',
  ),
)
