# SPDX-FileCopyrightText: Contributors to the HPCToolkit Project
#
# SPDX-License-Identifier: BSD-3-Clause

# Only spawn workflows for MRs or protected branches
workflow:
  auto_cancel:
    on_job_failure: all
    on_new_commit: interruptible
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"
      auto_cancel:
        on_job_failure: none
        on_new_commit: none
      when: always
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_PROTECTED != "true"
      when: never
    - when: always

stages:
  - individual tests
  - semi-fresh tests
  - configuration tests
  - code quality
  - pre-deploy checks
  - artifacts
  - deploy

variables:
  # Most jobs require the submodules, those that don't will override this
  GIT_SUBMODULE_STRATEGY: recursive

  # Add a transfer progress bar for artifacts
  TRANSFER_METER_FREQUENCY: 2s

  # Use fastzip to package caches and artifacts
  FF_USE_FASTZIP: "true"
  ARTIFACT_COMPRESSION_LEVEL: default
  CACHE_COMPRESSION_LEVEL: fastest

  # Retry various preliminary job stages (network errors)
  GET_SOURCES_ATTEMPTS: 3
  ARTIFACTS_DOWNLOAD_ATTEMPTS: 3
  EXECUTOR_JOB_SECTION_ATTEMPTS: 3

default:
  retry:
    max: 2
    when:
      - unknown_failure
      - api_failure
      - runner_system_failure
      - runner_unsupported
      - unmet_prerequisites
      - data_integrity_failure
    exit_codes: 68
  hooks:
    pre_get_sources_script:
      - >-
        GIT_TERMINAL_PROMPT=0 git ls-remote --quiet "$CI_REPOSITORY_URL" NONEXTISTENT_REF
        || exit 68

include:
  - local: ci/tests/gitlab.gitlab-ci.yml
    rules: &gitlab_com
      - if: $CI_SERVER_FQDN == "gitlab.com"
  - local: ci/tests/hpctoolkit.gitlab-ci.yml
    rules: &hpctoolkit_gitlab_com
      - if: $CI_SERVER_FQDN == "gitlab.com" && $CI_PROJECT_ID == "38709409"
  - local: ci/tests/data.gitlab-ci.yml
    rules: *hpctoolkit_gitlab_com
  - local: ci/lint.gitlab-ci.yml
    rules: *hpctoolkit_gitlab_com
  - local: ci/docs.gitlab-ci.yml
    rules: *gitlab_com
  - local: ci/spack/.gitlab-ci.yml
    rules: *hpctoolkit_gitlab_com
