// SPDX-FileCopyrightText: Contributors to the HPCToolkit Project
//
// SPDX-License-Identifier: BSD-3-Clause

// -*-Mode: C++;-*- // technically C99

//*****************************************************************************
// local includes
//*****************************************************************************

#include "level0-debug.h"



//*****************************************************************************
// interface functions
//*****************************************************************************


const char *
ze_result_to_string
(
  ze_result_t result
)
{
#define R2S(r) case r: return #r;
  switch (result) {
    R2S(ZE_RESULT_SUCCESS)
    R2S(ZE_RESULT_NOT_READY)
    R2S(ZE_RESULT_ERROR_DEVICE_LOST)
    R2S(ZE_RESULT_ERROR_OUT_OF_HOST_MEMORY)
    R2S(ZE_RESULT_ERROR_OUT_OF_DEVICE_MEMORY)
    R2S(ZE_RESULT_ERROR_MODULE_BUILD_FAILURE)
    R2S(ZE_RESULT_ERROR_MODULE_LINK_FAILURE)
    R2S(ZE_RESULT_ERROR_DEVICE_REQUIRES_RESET)
    R2S(ZE_RESULT_ERROR_DEVICE_IN_LOW_POWER_STATE)
    R2S(ZE_RESULT_EXP_ERROR_DEVICE_IS_NOT_VERTEX)
    R2S(ZE_RESULT_EXP_ERROR_VERTEX_IS_NOT_DEVICE)
    R2S(ZE_RESULT_EXP_ERROR_REMOTE_DEVICE)
#if ZE_MAJOR_VERSION(ZE_API_VERSION_CURRENT) >= 1 && ZE_MINOR_VERSION(ZE_API_VERSION_CURRENT) >= 7
    R2S(ZE_RESULT_EXP_ERROR_OPERANDS_INCOMPATIBLE)
    R2S(ZE_RESULT_EXP_RTAS_BUILD_RETRY)
    R2S(ZE_RESULT_EXP_RTAS_BUILD_DEFERRED)
#endif
    R2S(ZE_RESULT_ERROR_INSUFFICIENT_PERMISSIONS)
    R2S(ZE_RESULT_ERROR_NOT_AVAILABLE)
    R2S(ZE_RESULT_ERROR_DEPENDENCY_UNAVAILABLE)
    R2S(ZE_RESULT_WARNING_DROPPED_DATA)
    R2S(ZE_RESULT_ERROR_UNINITIALIZED)
    R2S(ZE_RESULT_ERROR_UNSUPPORTED_VERSION)
    R2S(ZE_RESULT_ERROR_UNSUPPORTED_FEATURE)
    R2S(ZE_RESULT_ERROR_INVALID_ARGUMENT)
    R2S(ZE_RESULT_ERROR_INVALID_NULL_HANDLE)
    R2S(ZE_RESULT_ERROR_HANDLE_OBJECT_IN_USE)
    R2S(ZE_RESULT_ERROR_INVALID_NULL_POINTER)
    R2S(ZE_RESULT_ERROR_INVALID_SIZE)
    R2S(ZE_RESULT_ERROR_UNSUPPORTED_SIZE)
    R2S(ZE_RESULT_ERROR_UNSUPPORTED_ALIGNMENT)
    R2S(ZE_RESULT_ERROR_INVALID_SYNCHRONIZATION_OBJECT)
    R2S(ZE_RESULT_ERROR_INVALID_ENUMERATION)
    R2S(ZE_RESULT_ERROR_UNSUPPORTED_ENUMERATION)
    R2S(ZE_RESULT_ERROR_UNSUPPORTED_IMAGE_FORMAT)
    R2S(ZE_RESULT_ERROR_INVALID_NATIVE_BINARY)
    R2S(ZE_RESULT_ERROR_INVALID_GLOBAL_NAME)
    R2S(ZE_RESULT_ERROR_INVALID_KERNEL_NAME)
    R2S(ZE_RESULT_ERROR_INVALID_FUNCTION_NAME)
    R2S(ZE_RESULT_ERROR_INVALID_GROUP_SIZE_DIMENSION)
    R2S(ZE_RESULT_ERROR_INVALID_GLOBAL_WIDTH_DIMENSION)
    R2S(ZE_RESULT_ERROR_INVALID_KERNEL_ARGUMENT_INDEX)
    R2S(ZE_RESULT_ERROR_INVALID_KERNEL_ARGUMENT_SIZE)
    R2S(ZE_RESULT_ERROR_INVALID_KERNEL_ATTRIBUTE_VALUE)
    R2S(ZE_RESULT_ERROR_INVALID_MODULE_UNLINKED)
    R2S(ZE_RESULT_ERROR_INVALID_COMMAND_LIST_TYPE)
    R2S(ZE_RESULT_ERROR_OVERLAPPING_REGIONS)
    R2S(ZE_RESULT_WARNING_ACTION_REQUIRED)
#if ZE_MAJOR_VERSION(ZE_API_VERSION_CURRENT) >= 1 && ZE_MINOR_VERSION(ZE_API_VERSION_CURRENT) >= 10
    R2S(ZE_RESULT_ERROR_INVALID_KERNEL_HANDLE)
#endif
#if ZE_MAJOR_VERSION(ZE_API_VERSION_CURRENT) >= 1 && ZE_MINOR_VERSION(ZE_API_VERSION_CURRENT) >= 7
    R2S(ZE_RESULT_EXT_RTAS_BUILD_RETRY)
    R2S(ZE_RESULT_EXT_RTAS_BUILD_DEFERRED)
    R2S(ZE_RESULT_EXT_ERROR_OPERANDS_INCOMPATIBLE)
#endif
#if ZE_MAJOR_VERSION(ZE_API_VERSION_CURRENT) >= 1 && ZE_MINOR_VERSION(ZE_API_VERSION_CURRENT) >= 13
    R2S(ZE_RESULT_ERROR_SURVIVABILITY_MODE_DETECTED)
#endif
    default:
    R2S(ZE_RESULT_ERROR_UNKNOWN)
  }
}
