# SPDX-FileCopyrightText: Contributors to the HPCToolkit Project
#
# SPDX-License-Identifier: MIT

libebl_lib = static_library(
  'libebl',
  'eblopenbackend.c',
  'eblclosebackend.c',
  'eblreloctypename.c',
  'eblsegmenttypename.c',
  'eblsectiontypename.c',
  'eblmachineflagname.c',
  'eblsymboltypename.c',
  'ebldynamictagname.c',
  'eblsectionname.c',
  'eblsymbolbindingname.c',
  'eblbackendname.c',
  'eblosabiname.c',
  'eblmachineflagcheck.c',
  'eblmachinesectionflagcheck.c',
  'eblreloctypecheck.c',
  'eblrelocvaliduse.c',
  'eblrelocsimpletype.c',
  'ebldynamictagcheck.c',
  'eblcorenotetypename.c',
  'eblobjnotetypename.c',
  'eblcorenote.c',
  'eblobjnote.c',
  'ebldebugscnp.c',
  'eblgotpcreloccheck.c',
  'eblcopyrelocp.c',
  'eblsectionstripp.c',
  'eblelfclass.c',
  'eblelfdata.c',
  'eblelfmachine.c',
  'ebl_check_special_symbol.c',
  'eblbsspltp.c',
  'eblretval.c',
  'eblreginfo.c',
  'eblnonerelocp.c',
  'eblrelativerelocp.c',
  'eblsysvhashentrysize.c',
  'eblauxvinfo.c',
  'eblcheckobjattr.c',
  'ebl_check_special_section.c',
  'eblabicfi.c',
  'eblstother.c',
  'eblinitreg.c',
  'ebldwarftoregno.c',
  'eblnormalizepc.c',
  'eblunwind.c',
  'eblresolvesym.c',
  'eblcheckreloctargettype.c',
  'ebl_data_marker_symbol.c',
  pic: true,
  include_directories: include_directories('../libelf', '../libdw', '../libasm'),
)
