#!/bin/sh -ex

# SPDX-FileCopyrightText: Contributors to the HPCToolkit Project
#
# SPDX-License-Identifier: Apache-2.0

perf_check="$1"
hpcproftt="$2"
hpcrun="$3"
tstexe_1loop="$4"

trap 'rm -rf "$tmpdir"' EXIT
tmpdir=$(mktemp --directory)

if ! "$perf_check"; then exit 77; fi

"$hpcrun" -o "$tmpdir"/m -e '{perf::cpu-clock,perf::task-clock}'@f100 "$tstexe_1loop"

for hpcfile in ${tmpdir}/m/*.hpcrun; do
    echo "Checking $hpcfile with $hpcproftt"
    num_metrics=$("$hpcproftt" -g $hpcfile  | grep "val-fmt" | wc -l)
    if [ "$num_metrics" -ne 2 ]; then
        exit 78
    fi
done
