#!/bin/sh -ex

# SPDX-FileCopyrightText: Contributors to the HPCToolkit Project
#
# SPDX-License-Identifier: Apache-2.0

perf_check="$1"
hpctesttool="$2"
hpcrun="$3"
tstexe_1loop="$4"

trap 'rm -rf "$tmpdir"' EXIT
tmpdir=$(mktemp --directory)

# Test if perf_event_open syscall is actually functional (handles container seccomp restrictions)
if ! "$perf_check"; then exit 77; fi

"$hpcrun" -o "$tmpdir"/m -e perf::cpu-clock@f100 --enable-auditor "$tstexe_1loop"
"$hpctesttool" test produces-profiles "$tmpdir"/m \
  '^NODE [^A-Z]+\s+(CORE [^A-Z]+\s+)?THREAD 0/0:logical$'
