#!/bin/sh -ex

# SPDX-FileCopyrightText: Contributors to the HPCToolkit Project
#
# SPDX-License-Identifier: Apache-2.0

hpctesttool="$1"
hpcrun="$2"
hpcstruct="$3"
hpcprof="$4"
shift 4  # Remaining arguments are the app command line

trap 'rm -rf "$tmpdir"' EXIT
tmpdir=$(mktemp --directory)

"$hpcrun" -o "$tmpdir"/m "$@"
"$hpcstruct" -o "$tmpdir"/exe.hpcstruct "$(command -v "$1")"
"$hpcprof" -j1 -S "$tmpdir"/exe.hpcstruct -o "$tmpdir"/d "$tmpdir"/m
"$hpctesttool" test check-db "$tmpdir"/d
