# SPDX-FileCopyrightText: Contributors to the HPCToolkit Project
#
# SPDX-License-Identifier: Apache-2.0

.rhel8:compile:
  extends: .compile
  script:
    - meson setup builddir/ -Dwerror=true -Ddyninst:werror=false -Dxed:werror=false -Dlibunwind:werror=false -Doptimization=2 -Ddebug=false -Db_ndebug=false
    - cd builddir/
    - meson test --print-errorlogs 'hpctoolkit:*'
    - meson compile

.rhel8:test cpu:
  extends: .test
  script:
    - cd builddir/
    - meson test --print-errorlogs 'hpctoolkit:*'

rhel8 amd64:compile:
  extends: .rhel8:compile
  rules:
    - if: &on_gitlab $CI_SERVER_FQDN == "gitlab.com"
  tags: [$GITLAB_SAAS_LINUX_MAX_AMD64]
  image: &image_amd64
    name: registry.gitlab.com/hpctoolkit/rtt-images:1.0.0-rhel8
    docker:
      platform: linux/amd64

rhel8 amd64:test cpu:
  extends: .rhel8:test cpu
  needs: [rhel8 amd64:compile]
  rules:
    - if: *on_gitlab
  tags: [$GITLAB_SAAS_LINUX_MAX_AMD64]
  image: *image_amd64
