# SPDX-FileCopyrightText: Contributors to the HPCToolkit Project
#
# SPDX-License-Identifier: Apache-2.0

.rhel8:compile:
  extends: .compile
  script:
    - mkdir tmp/
    - meson setup tmp/builddir-${BUILD_SLUG}/ -Dwerror=true -Doptimization=2 -Ddebug=false -Db_ndebug=false
    - cd tmp/builddir-${BUILD_SLUG}/
    - meson test --print-errorlogs 'hpctoolkit:*'
    - meson compile

.rhel8:test cpu:
  extends: .test
  script:
    - cd tmp/builddir-${BUILD_SLUG}/
    - meson test --print-errorlogs 'hpctoolkit:*'

rhel8 amd64:compile:
  extends: .rhel8:compile
  variables:
    BUILD_SLUG: rhel8-amd64
  rules:
    - if: &on_gitlab $CI_SERVER_FQDN == "gitlab.com"
  tags: [$GITLAB_SAAS_LINUX_MAX_AMD64]
  image: &image_amd64
    name: registry.gitlab.com/hpctoolkit/rtt-images:1.0.0-rhel8@sha256:7b3173bcdc96237dcb3fdf8074342aadee0c1e79e651d8d3264ed836271c33c9
    docker:
      platform: linux/amd64

rhel8 amd64:test cpu:
  extends: .rhel8:test cpu
  variables:
    BUILD_SLUG: rhel8-amd64
  needs: [rhel8 amd64:compile]
  rules:
    - if: *on_gitlab
  tags: [$GITLAB_SAAS_LINUX_MAX_AMD64]
  image: *image_amd64
