# SPDX-FileCopyrightText: Contributors to the HPCToolkit Project
#
# SPDX-License-Identifier: Apache-2.0

.ubuntu22.04:compile:
  extends: .compile
  script:
    - mkdir tmp/
    - meson setup tmp/builddir-${BUILD_SLUG}/ -Dwerror=true -Doptimization=2 -Ddebug=false -Db_ndebug=false
    - cd tmp/builddir-${BUILD_SLUG}/
    - meson test --print-errorlogs 'hpctoolkit:*'
    - meson compile

.ubuntu22.04:test cpu:
  extends: .test
  script:
    - cd tmp/builddir-${BUILD_SLUG}/
    - meson test --print-errorlogs 'hpctoolkit:*'

.ubuntu22.04:compile+test:
  extends: .compile+test
  script:
    - mkdir tmp/
    - meson setup tmp/builddir-${BUILD_SLUG}/ -Dwerror=true -Dbuildtype=debugoptimized
    - cd tmp/builddir-${BUILD_SLUG}/
    - meson test --print-errorlogs 'hpctoolkit:*'
    - meson compile

ubuntu22.04 amd64:compile:
  extends: .ubuntu22.04:compile
  variables:
    BUILD_SLUG: ubuntu22.04-amd64
  rules:
    - if: &on_gitlab $CI_SERVER_FQDN == "gitlab.com"
  tags: [$GITLAB_SAAS_LINUX_MAX_AMD64]
  image: &image_amd64
    name: registry.gitlab.com/hpctoolkit/rtt-images:1.0.0-ubuntu22.04@sha256:86b36864e3b6ff0893c26df391928854bbc202ddd8f283d727276091dd182e60
    docker:
      platform: linux/amd64

ubuntu22.04 amd64:test cpu:
  extends: .ubuntu22.04:test cpu
  variables:
    BUILD_SLUG: ubuntu22.04-amd64
  needs: [ubuntu22.04 amd64:compile]
  rules:
    - if: *on_gitlab
  tags: [$GITLAB_SAAS_LINUX_MAX_AMD64]
  image: *image_amd64

ubuntu22.04 arm64:compile:
  extends: .ubuntu22.04:compile
  variables:
    BUILD_SLUG: ubuntu22.04-arm64
  rules:
    - if: *on_gitlab
  tags: [$GITLAB_SAAS_LINUX_MAX_ARM64]
  image: &image_arm64
    name: registry.gitlab.com/hpctoolkit/rtt-images:1.0.0-ubuntu22.04@sha256:86b36864e3b6ff0893c26df391928854bbc202ddd8f283d727276091dd182e60
    docker:
      platform: linux/arm64

ubuntu22.04 arm64:test cpu:
  extends: .ubuntu22.04:test cpu
  variables:
    BUILD_SLUG: ubuntu22.04-arm64
  needs: [ubuntu22.04 arm64:compile]
  rules:
    - if: *on_gitlab
  tags: [$GITLAB_SAAS_LINUX_MAX_ARM64]
  image: *image_arm64

# NB: Current GPU vendor runtimes don't support ppc64le, so we use a merged compile/test
# architecture for better performance.
ubuntu22.04 ppc64le:test:
  extends: .ubuntu22.04:compile+test
  variables:
    BUILD_SLUG: ubuntu22.04-ppc64le
  rules:
    - if: $HPCTOOLKIT_LINUX_MAX_PPC64LE
  tags: [$HPCTOOLKIT_LINUX_MAX_PPC64LE]
  image:
    name: registry.gitlab.com/hpctoolkit/rtt-images:1.0.0-ubuntu22.04@sha256:86b36864e3b6ff0893c26df391928854bbc202ddd8f283d727276091dd182e60
    docker:
      platform: linux/ppc64le

ubuntu22.04 ppc64le:test:hpsf:
  extends: ubuntu22.04 ppc64le:test
  variables:
    BUILD_SLUG: ubuntu22.04-ppc64le-hpsf
  rules:
    - if: &on_hpsf $CI_SERVER_FQDN == "gitlab.spack.io"
  tags: [hpsf-ppc64le]
