# SPDX-FileCopyrightText: Contributors to the HPCToolkit Project
#
# SPDX-License-Identifier: BSD-3-Clause

# Generate just the documentation, and expose all the possible formats as artifacts.
documentation:
  stage: artifacts
  image: $PREDEPS_IMAGE_DEV_AMD64
  needs: ["predeps: [dev-amd64]"]
  tags: [saas-linux-small-amd64]
  script:
    - meson setup -Dmanual=enabled -Dmanual_pdf=enabled builddir/
    - meson compile -C builddir/ html hpctoolkit.epub hpctoolkit.pdf
    - >-
      mv -t .
      builddir/doc/src/html builddir/doc/src/hpctoolkit.epub builddir/doc/src/hpctoolkit.pdf
  artifacts:
    expose_as: "Rendered documentation"
    paths:
      # HTML version is the primary one exposed
      - html/index.html
      - html/
      # Single-file variants are also available
      - hpctoolkit.epub
      - hpctoolkit.pdf

# Publish the rendered documentation to GitLab pages for easy browsing from the web.
# FIXME: Currently this only happens for the default branch. Eventually we should extend this to
# include protected tags (releases) as well, once multiple deployments are easy.
# See https://gitlab.com/gitlab-org/gitlab/-/issues/422145 and https://gitlab.com/groups/gitlab-org/-/epics/10914.
pages:
  stage: deploy
  image: docker.io/alpine
  needs: [documentation]
  rules:
    - if: >-
        ($ENABLE_HPCTOOLKIT_CUSTOM_RUNNERS == "" || $ENABLE_HPCTOOLKIT_CUSTOM_RUNNERS == null)
        && $CI_COMMIT_REF_PROTECTED == "false"
        && $CI_MERGE_REQUEST_IID
        && $CI_PROJECT_ID != $CI_MERGE_REQUEST_PROJECT_ID
      when: never
    - if: $CI_COMMIT_REF_PROTECTED == "true" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - mv -T html/ public/
    - echo "Deploying documentation to ${CI_PAGES_URL}"
  artifacts:
    paths: [public/]
