# SPDX-FileCopyrightText: Contributors to the HPCToolkit Project
#
# SPDX-License-Identifier: Apache-2.0

# Lint the codebase with clang-tidy, to identify various common code issues that are more expensive
# to produce and aren't suitable for compiler warnings. Fixing issues identified here isn't and
# never will be enforced, but it does give rich insight into the quality of the code itself.
.clang-tidy:
  extends: .needs verify
  stage: code quality
  image: registry.gitlab.com/hpctoolkit/rtt-images:1.0.0-aio@sha256:aed3071b8690dbdf3e2b4fec2071b47680c0be171e1a5613e43f425b55b67c2c
  cache:
    key: ccache-clang-tidy
    when: always
    paths:
      - .ccache
  variables:
    CCACHE_DIR: "$CI_PROJECT_DIR/.ccache"
clang-tidy:
  extends: .clang-tidy
  tags: [saas-linux-xlarge-amd64]
  script:
    - meson setup --backend=ninja builddir
    - ninja -C builddir/
    - ninja -C builddir/ clang-tidy > clang-tidy.raw.txt || true
    - ./ci/cc-diagnostics.py clang-tidy clang-tidy.cq.json clang-tidy.raw.txt
  artifacts:
    reports:
      codequality: clang-tidy.cq.json
# Same as clang-tidy, but this time apply the fix-its and produce a patch for human review.
clang-tidy-fix:
  extends: .clang-tidy
  tags: [saas-linux-xlarge-amd64]
  script:
    - meson setup --backend=ninja builddir
    - ninja -C builddir/
    - ninja -C builddir/ clang-tidy-fix > /dev/null || true
    - git diff --full-index > clang-tidy-fixits.patch
    - if ! test -s clang-tidy-fixits.patch; then rm clang-tidy-fixits.patch; fi
  artifacts:
    paths:
      - clang-tidy-fixits.patch
