#!/bin/sh -ex

# SPDX-FileCopyrightText: Contributors to the HPCToolkit Project
#
# SPDX-License-Identifier: Apache-2.0

hpctesttool="$1"
hpcstruct="$2"
binary="$3"
shift 3  # Remaining arguments go to the hpctesttool

trap 'rm -rf "$tmpdir"' EXIT
tmpdir=$(mktemp --directory)

"$hpcstruct" -o "$tmpdir"/s.hpcstruct "$binary"
"$hpctesttool" test match-struct "$tmpdir"/s.hpcstruct "$binary" "$@"
