#!/bin/sh -ex

# SPDX-FileCopyrightText: Contributors to the HPCToolkit Project
#
# SPDX-License-Identifier: Apache-2.0

hpctesttool="$1"
auditor="$2"
tstexe_dtv="$2"

LD_AUDIT="$auditor" "$tstexe_dtv"
