#!/bin/sh -ex

# SPDX-FileCopyrightText: Contributors to the HPCToolkit Project
#
# SPDX-License-Identifier: BSD-3-Clause

hpctesttool="$1"
canonical="$2"
shift 2  # Remaining arguments are the hpcprof command line

trap 'rm -rf "$tmpdir"' EXIT
tmpdir=$(mktemp --directory --tmpdir=.)

"$@" -o "$tmpdir"/d
"$hpctesttool" test db-compare "$tmpdir"/d "$canonical"
