#!/bin/sh -ex

# SPDX-FileCopyrightText: Contributors to the HPCToolkit Project
#
# SPDX-License-Identifier: Apache-2.0

hpctesttool="$1"
hpcprof="$2"
meas="$3"

trap 'rm -rf "$tmpdir"' EXIT
tmpdir=$(mktemp --directory)

if ls -1 "$meas"/*.hpctrace > /dev/null 2>&1
then tracearg=--trace
else tracearg=--no-trace
fi

"$hpcprof" -j1 -o "$tmpdir"/d.1 "$meas"
"$hpctesttool" test check-db "$tracearg" "$tmpdir/d.1"

"$hpcprof" -j1 -o "$tmpdir"/d.2 --no-traces "$meas"
"$hpctesttool" test check-db --no-trace "$tmpdir/d.2"
